'use client';

// topState
import ChartRunning from '@/app/uiux/components/modules/topState/ChartRunning';
import ChartState from '@/app/uiux/components/modules/topState/ChartState';
import ChartState2 from '@/app/uiux/components/modules/topState/ChartState2';
import ChartOperation from '@/app/uiux/components/modules/topState/ChartOperation';
import ChartOperation2 from '@/app/uiux/components/modules/topState/ChartOperation2';
import ChartToday from '@/app/uiux/components/modules/topState/ChartToday';
import ChartMonth from '@/app/uiux/components/modules/topState/ChartMonth';
import TopStateCenter from '@/app/uiux/components/modules/topState/TopStateCenter';

// topFilter
import ColorChipType2 from '@/app/uiux/components/modules/topFilter/ColorChipType2';
import SearchArea from '@/app/uiux/components/modules/topFilter/SearchArea';
import PageTitle from '@/app/uiux/components/modules/PageTitle';
import titleIcon from '@/assets/images/icon/detail3.png';

// monitoring
import List2 from '@/app/uiux/components/modules/monitoring/ListType2';

// zoom
import { useState } from 'react';
import { Dialog, DialogTitle, DialogContent, IconButton, Button } from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';

export default function DashboardPack() {
  // --- Chart Data ---
  const chartData = { total: 20, running: 15 };
  const chartData2 = [
    { name: 'Charge', value: 20 },
    { name: 'Discharge', value: 15 },
    { name: 'Rest', value: 10 },
    { name: 'Rest(ISO)', value: 10 },
    { name: 'Pattern', value: 15 },
    { name: 'ChargeMap', value: 10 },
  ];
  const chartData3 = [
    { name: '대기', value: 13 },
    { name: '진행중', value: 2 },
    { name: '일시정지', value: 1 },
    { name: '알람', value: 1 },
  ];
  const chartData4 = [
    { name: '방전', value: 280 },
    { name: '충전', value: 580 },
  ];
  const chartData5 = [
    { name: '1', charge: 30, discharge: 50 },
    { name: '2', charge: 60, discharge: 20 },
    { name: '3', charge: 40, discharge: 50 },
    { name: '4', charge: 30, discharge: 50 },
    { name: '5', charge: 60, discharge: 20 },
    { name: '6', charge: 40, discharge: 50 },
  ];

  // --- Monitoring List Data ---
  const listData = [
    {
      id: 1, // id
      x: 1, // x 좌표
      y: 1, // y 좌표
      title: '300A-1A', // 타이틀
      check: true, // 체크표시
      ready: false, // '신규장비 업데이트 예정' 표시
      shutdown: true, // 테두리 점등
      operation: 'ongoing', // 공정: ongoing, completion, available, stop
      icon: 'success', // 아이콘: success, stay, error
      temp1: '17℃', // 온도 1
      temp2: '25℃', // 온도 2
      ch1: 8, // 채널 1
      ch2: 0, // 채널 2
      ch3: 0, // 채널 3
      memo: true, // 메모
      memoText: [
        // 메모 내용
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '비고: 00만 km RPT 측정 후 내구 재개 [250923-24] 칠러 냉각수 보증 시험 일시정지 _이정우', // 메모 textarea
    },
    {
      id: 2,
      x: 2,
      y: 1,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'completion',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '3',
    },
    {
      id: 3,
      x: 3,
      y: 1,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'completion',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '3',
    },
    {
      id: 4,
      x: 4,
      y: 1,
      title: '300A-4A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'available',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '4',
    },
    {
      id: 5,
      x: 5,
      y: 1,
      title: '신규장비 업데이트 예정',
      check: false,
      ready: true,
      shutdown: false,
      operation: 'ongoing',
      icon: 'error',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '5',
    },
    {
      id: 6,
      x: 6,
      y: 1,
      title: '신규장비 업데이트 예정',
      check: false,
      ready: true,
      shutdown: true,
      operation: 'stop',
      icon: 'error',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '6',
    },
    {
      id: 7,
      x: 7,
      y: 1,
      title: '신규장비 업데이트 예정',
      check: false,
      ready: true,
      shutdown: false,
      operation: 'completion',
      icon: 'error',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '7',
    },
    {
      id: 8,
      x: 8,
      y: 1,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'available',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 9,
      x: 9,
      y: 1,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'ongoing',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 10,
      x: 10,
      y: 1,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'completion',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 11,
      x: 11,
      y: 1,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'available',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 0,
      ch2: 0,
      ch3: 0,
      memo: false,
      memoText: [],
      memoTotal: '8',
    },
    {
      id: 12,
      x: 12,
      y: 1,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'stop',
      icon: 'error',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 13,
      x: 13,
      y: 1,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'ongoing',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 14,
      x: 14,
      y: 1,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'completion',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    // *
    // * line 2
    // *
    {
      id: 2_1,
      x: 1,
      y: 2,
      title: '300A-1A',
      check: true,
      ready: false,
      shutdown: true,
      operation: 'ongoing',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '비고: 00만 km RPT 측정 후 내구 재개 [250923-24] 칠러 냉각수 보증 시험 일시정지 _이정우',
    },
    {
      id: 2_2,
      x: 2,
      y: 2,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'completion',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '3',
    },
    {
      id: 2_3,
      x: 3,
      y: 2,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'completion',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '3',
    },
    {
      id: 2_4,
      x: 4,
      y: 2,
      title: '300A-4A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'available',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '4',
    },
    {
      id: 2_5,
      x: 5,
      y: 2,
      title: '신규장비 업데이트 예정',
      check: false,
      ready: true,
      shutdown: false,
      operation: 'ongoing',
      icon: 'error',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '5',
    },
    {
      id: 2_6,
      x: 6,
      y: 2,
      title: '신규장비 업데이트 예정',
      check: false,
      ready: true,
      shutdown: false,
      operation: 'stop',
      icon: 'error',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '6',
    },
    {
      id: 2_7,
      x: 7,
      y: 2,
      title: '신규장비 업데이트 예정',
      check: false,
      ready: true,
      shutdown: false,
      operation: 'completion',
      icon: 'error',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '7',
    },
    {
      id: 2_8,
      x: 8,
      y: 2,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'available',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 2_9,
      x: 9,
      y: 2,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'ongoing',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 2_10,
      x: 10,
      y: 2,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'completion',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 2_11,
      x: 11,
      y: 2,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'available',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 0,
      ch2: 0,
      ch3: 0,
      memo: false,
      memoText: [],
      memoTotal: '8',
    },
    {
      id: 2_12,
      x: 12,
      y: 2,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'stop',
      icon: 'error',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 2_13,
      x: 13,
      y: 2,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'ongoing',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 2_14,
      x: 14,
      y: 2,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'completion',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    // *
    // * line 3
    // *
    {
      id: 3_1,
      x: 1,
      y: 3,
      title: '300A-1A',
      check: true,
      ready: false,
      shutdown: true,
      operation: 'ongoing',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '비고: 00만 km RPT 측정 후 내구 재개 [250923-24] 칠러 냉각수 보증 시험 일시정지 _이정우',
    },
    {
      id: 3_14,
      x: 14,
      y: 3,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'available',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    // *
    // * line 4
    // *
    {
      id: 4_1,
      x: 1,
      y: 4,
      title: '300A-1A',
      check: true,
      ready: false,
      shutdown: true,
      operation: 'ongoing',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '비고: 00만 km RPT 측정 후 내구 재개 [250923-24] 칠러 냉각수 보증 시험 일시정지 _이정우',
    },
    {
      id: 4_2,
      x: 2,
      y: 4,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'completion',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '3',
    },
    {
      id: 4_3,
      x: 3,
      y: 4,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'completion',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '3',
    },
    {
      id: 4_4,
      x: 4,
      y: 4,
      title: '300A-4A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'available',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '4',
    },
    {
      id: 4_5,
      x: 5,
      y: 4,
      title: '신규장비 업데이트 예정',
      check: false,
      ready: true,
      shutdown: false,
      operation: 'ongoing',
      icon: 'error',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '5',
    },
    {
      id: 4_6,
      x: 6,
      y: 4,
      title: '신규장비 업데이트 예정',
      check: false,
      ready: true,
      shutdown: false,
      operation: 'stop',
      icon: 'error',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '6',
    },
    {
      id: 4_7,
      x: 7,
      y: 4,
      title: '신규장비 업데이트 예정',
      check: false,
      ready: true,
      shutdown: false,
      operation: 'completion',
      icon: 'error',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '7',
    },
    {
      id: 4_8,
      x: 8,
      y: 4,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'available',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 4_9,
      x: 9,
      y: 4,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'ongoing',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 4_10,
      x: 10,
      y: 4,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'completion',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 4_11,
      x: 11,
      y: 4,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'available',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 0,
      ch2: 0,
      ch3: 0,
      memo: false,
      memoText: [],
      memoTotal: '8',
    },
    {
      id: 4_13,
      x: 13,
      y: 4,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'ongoing',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 4_14,
      x: 14,
      y: 4,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'completion',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    // *
    // * line 5
    // *
    {
      id: 5_1,
      x: 1,
      y: 5,
      title: '300A-1A',
      check: true,
      ready: false,
      shutdown: true,
      operation: 'ongoing',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '비고: 00만 km RPT 측정 후 내구 재개 [250923-24] 칠러 냉각수 보증 시험 일시정지 _이정우',
    },
    {
      id: 5_2,
      x: 2,
      y: 5,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'completion',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '3',
    },
    {
      id: 5_3,
      x: 3,
      y: 5,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'completion',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '3',
    },
    {
      id: 5_4,
      x: 4,
      y: 5,
      title: '300A-4A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'available',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '4',
    },
    {
      id: 5_5,
      x: 5,
      y: 5,
      title: '신규장비 업데이트 예정',
      check: false,
      ready: true,
      shutdown: false,
      operation: 'ongoing',
      icon: 'error',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '5',
    },
    {
      id: 5_6,
      x: 6,
      y: 5,
      title: '신규장비 업데이트 예정',
      check: false,
      ready: true,
      shutdown: false,
      operation: 'stop',
      icon: 'error',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '6',
    },
    {
      id: 5_7,
      x: 7,
      y: 5,
      title: '신규장비 업데이트 예정',
      check: false,
      ready: true,
      shutdown: false,
      operation: 'completion',
      icon: 'error',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '7',
    },
    {
      id: 5_8,
      x: 8,
      y: 5,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'available',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 5_9,
      x: 9,
      y: 5,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'ongoing',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 5_10,
      x: 10,
      y: 5,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'completion',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 5_11,
      x: 11,
      y: 5,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'available',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 0,
      ch2: 0,
      ch3: 0,
      memo: false,
      memoText: [],
      memoTotal: '8',
    },
    {
      id: 5_13,
      x: 13,
      y: 5,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'ongoing',
      icon: 'success',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
    {
      id: 5_14,
      x: 14,
      y: 5,
      title: '300A-3A',
      check: false,
      ready: false,
      shutdown: false,
      operation: 'completion',
      icon: 'stay',
      temp1: '17℃',
      temp2: '25℃',
      ch1: 8,
      ch2: 0,
      ch3: 0,
      memo: true,
      memoText: [
        { ch: 'CH 9', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 10', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 11', status: 'completion', statusText: '완료', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 12', status: 'available', statusText: '사용가능', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 13', status: 'ongoing', statusText: '진행중', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
        { ch: 'CH 14', status: 'stop', statusText: '정지', text: 'LME2-00105', text2: 'CC Cycle (45℃)' },
      ],
      memoTotal: '8',
    },
  ];

  // chart zoom
  const [isZoomOpen, setIsZoomOpen] = useState(false);

  // card zoom
  const [isZoomOpen2, setIsZoomOpen2] = useState(false);

  return (
    <>
      {/* --- topState Section --- */}
      <section className="topState">
        <h2 className="ir">상단 기능 화면</h2>
        <div className="left">
          <ChartRunning title="장비가동률" total={chartData.total} running={chartData.running} />
          <ChartState title="장비현황" data={chartData2} />
          <ChartOperation title="장비가동현황" data={chartData3} />
          <Button className="btnZoom" onClick={() => setIsZoomOpen(true)}>
            확대보기
          </Button>
        </div>
        <div className="center">
          <TopStateCenter />
        </div>
        <div className="right">
          <ChartToday title="오늘 전력량" data={chartData4} />
          <ul className="legend">
            <li className="charge">충전</li>
            <li>방전</li>
          </ul>
          <ChartMonth title="월별 전력량" data={chartData5} />
        </div>
      </section>

      {/* --- topFilter Section --- */}
      <section className="topFilter">
        <div className="left">
          <PageTitle title="장비상세" icon={titleIcon} />

          <Button className="btnZoom" onClick={() => setIsZoomOpen2(true)}>
            확대보기
          </Button>
          <SearchArea />
        </div>
        <div className="right">
          <ColorChipType2 />
        </div>
      </section>

      {/* --- monitoring Section --- */}
      <section className="monitoring type2">
        <h2 className="ir">모니터링 화면</h2>
        <div className="innerWrapper">
          <List2 listData={listData} />
        </div>
      </section>

      {/* chart zoom dialog */}
      <Dialog className="dialogCont wide" open={isZoomOpen} onClose={() => setIsZoomOpen(false)}>
        <div className="modalWrapper chartZoom">
          {/* 제목 + 닫기버튼 */}
          <DialogTitle className="tit">
            <span></span>
            <IconButton className="btnClose" onClick={() => setIsZoomOpen(false)}>
              <CloseIcon />
            </IconButton>
          </DialogTitle>

          <DialogContent className="contents">
            <div className="topState">
              <div className="left">
                <ChartRunning title="장비가동률" total={chartData.total} running={chartData.running} />
                <ChartState2 title="장비현황" data={chartData2} />
                <ChartOperation2 title="장비가동현황" data={chartData3} />
              </div>
            </div>
          </DialogContent>
        </div>
      </Dialog>

      {/* card zoom dialog */}
      <Dialog className="dialogCont full" open={isZoomOpen2} onClose={() => setIsZoomOpen2(false)}>
        <div className="modalWrapper chartZoom">
          {/* 제목 + 닫기버튼 */}
          <DialogTitle className="tit">
            <span></span>
            <IconButton className="btnClose" onClick={() => setIsZoomOpen2(false)}>
              <CloseIcon />
            </IconButton>
          </DialogTitle>

          <DialogContent className="contents">
            <section className="topFilter">
              <div className="left">
                <PageTitle title="장비상세" icon={titleIcon} />
              </div>
              <div className="right">
                <ColorChipType2 />
              </div>
            </section>

            {/* monitoring */}
            <section className="monitoring type2">
              <h2 className="ir">모니터링 화면</h2>
              <div className="innerWrapper">
                <List2 listData={listData} />
              </div>
            </section>
          </DialogContent>
        </div>
      </Dialog>
    </>
  );
}
